### ISSUE TITLE
Account Details DataConnect - Large Amounts of 304s

### ISSUE THREAD

**Issue by nbsaskpoly** [ellucian-developer/experience-sdk-sample-extensions#6]
Hello,
After an Ellucian conference, the Account Details card was advertised to some of our management as a production ready card.

I have since implemented it into our experience portal, along with the associated data connect API. The card and data connect API appear are working. We tested them quite thoroughly in our test environment

However, after releasing it to production, we are getting an overwhelming amount of 304 errors on our Ethos Integration Reports page.

First I tried to contact Ellucian Support, but they're not able to reproduce the issue and have asked me to try to contact you as to where the 304 errors are coming from, as well as how we could address them.

The case number for our support case is CSC03432766

Here is an example of the errors we are getting in our report page:

![image002 (1)](https://github.com/user-attachments/assets/a3ec9174-bfdf-40e4-bfd4-33590490b52e)

we are receiving an overwhelming amount of these, and it's making it a challenge to find errors from other parts of our domain.

**Comment by ellucianBret** [comment]
Not sure who told you it was "production ready". That term might mean different things to different people. It is in a repo named experience-ethos-examples. We expect them to work, but they are not officially supported. However, using an Experience extension that calls Data Connect Serverless API(s) is supported!! I will followup with the support case on this as well.

FYI, this repo isn't the repo you got the code from :) It is over here.
https://github.com/ellucian-developer/experience-ethos-examples
Can you create your issue on the other repo so it will be less confusing?

As far as I know, 304s should not be returned by Data Connect Serverless. 
Can you capture a har file when this happens? Or tight window on the time when this happens to help us go through logs?
The har file or network traffic will include a response header called correlation-id. It would be most helpful in tracking this down.

Bret

**Comment by ellucianBret** [comment]
I see you did capture a har file in the support case. I will follow up with the team there.

Bret

**Comment by ellucianBret** [comment]
@nbsaskpoly it looks like the har only includes successful calls to the API. Have you been able to duplicate it with a browser? Or are you just seeing it in the Ethos logs?


Bret

**Comment by glmclellan** [comment]
Nick is current off until Oct 7th. Once he returns he will follow up with your request.

Gerry

**Comment by nbsaskpoly** [comment]
Yeah my mistake, I'll open the issue in the other repo

https://github.com/ellucian-developer/experience-ethos-examples/issues/39
